version: '2'
services:
  file_postgres:
      image: postgres:9.5
      container_name: postgres
      environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_USER: developer
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_DB: fileupload
      volumes:
        - postgres_db:/var/lib/postgresql/data/pgdata
      ports:
        - "5432:5432"
  file_oracle:
      image: wnameless/oracle-xe-11g
      container_name: oracle
      volumes:
        - oracle_xe:/u01/app/oracle
      ports:
        - "49160:22"
        - "49161:1521"
volumes:
  postgres_db:
  oracle_xe:
