
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS RF_USER_ROLES;
DROP TABLE IF EXISTS USER_ROLE_MAP;

DROP SEQUENCE IF EXISTS USER_ID_SEQ;
DROP SEQUENCE IF EXISTS USER_ROLE_MAP_ID_SEQ;


CREATE TABLE IF NOT EXISTS USERS (
    USER_ID     INTEGER PRIMARY KEY,
    LOGON_ID    VARCHAR(15) UNIQUE NOT NULL,
    FIRST_NAME  VARCHAR(50) NOT NULL,
    LAST_NAME   VARCHAR(50),
    MIDDLE_NAME VARCHAR(50),
    EMAIL       VARCHAR(100),
    PASSWORD    VARCHAR(255),
    CREATED_BY  VARCHAR(15) NOT NULL,
    CREATED_DATE TIMESTAMP WITHOUT TIME ZONE,
    LAST_UPDATED_BY  VARCHAR(15) NOT NULL,
    LAST_UPDATED_DATE  TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS RF_USER_ROLES (
    CODE       VARCHAR(50) PRIMARY KEY,
    DESCRIPTION     VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS USER_ROLE_MAP (
    USER_ROLE_MAP_ID   INTEGER PRIMARY KEY,
    USER_ID       INTEGER NOT NULL,
    ROLE_CODE     VARCHAR(50) NOT NULL,
    CREATED_BY    VARCHAR(15) NOT NULL,
    CREATED_DATE  TIMESTAMP WITHOUT TIME ZONE,
    LAST_UPDATED_BY VARCHAR(15) NOT NULL,
    LAST_UPDATED_DATE TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT USER_ROLE_MAP_USER_FK  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
   CONSTRAINT USER_ROLE_MAP_ROLE_FK  FOREIGN KEY (ROLE_CODE) REFERENCES RF_USER_ROLES(CODE)
);

CREATE SEQUENCE IF NOT EXISTS USER_ID_SEQ;
CREATE SEQUENCE IF NOT EXISTS USER_ROLE_MAP_ID_SEQ;


INSERT INTO RF_USER_ROLES (CODE, DESCRIPTION) VALUES ('FILE_UPLOAD', 'File upload Permissions');
INSERT INTO RF_USER_ROLES (CODE, DESCRIPTION) VALUES ('FILE_DOWNLOAD', 'File download Permissions');
INSERT INTO RF_USER_ROLES (CODE, DESCRIPTION) VALUES ('FILE_DELETE', 'File delete Permissions');


